// import { useState, useMemo } from "react";
// import jsPDF from "jspdf";
// import ReactMarkdown from "react-markdown";
// import { FileText, Download } from "lucide-react";
// import { ScrollArea } from "@/components/ui/scroll-area";
// import { toast } from "@/hooks/use-toast";
// import { allSectionKeys, mockAnalyzedContent } from "./data";

// const DocumentPreview = ({ isAnalyzed, transcriptContent }) => {
//   const [format, setFormat] = useState("pdf");

//   const fullDocument = useMemo(() => {
//     if (!isAnalyzed) return null;
//     let transcriptText = "";
//     try {
//       const msgs = JSON.parse(transcriptContent);
//       transcriptText = msgs.map((m) => `[${m.time}] ${m.speaker}: ${m.text}`).join("\n\n");
//     } catch { transcriptText = transcriptContent; }
//     const allSections = allSectionKeys.map(s => mockAnalyzedContent[s.key]).join("\n\n---\n\n");
//     const fullMarkdown = `${allSections}\n\n---\n\n# Full Transcript\n\n${transcriptText}`;
//     return { markdown: fullMarkdown, transcript: transcriptText };
//   }, [isAnalyzed, transcriptContent]);

//   const handleDownload = () => {
//     if (!fullDocument) return;
//     const stripMd = (text) => text.replace(/#{1,6}\s?/g, "").replace(/\*\*/g, "").replace(/\*/g, "").replace(/`/g, "").replace(/---/g, "");

//     if (format === "doc") {
//       const sectionsHtml = allSectionKeys.map(s => {
//         const content = mockAnalyzedContent[s.key];
//         return content.split("\n").map(line => {
//           if (line.startsWith("## ")) return `<h2 style="font-size: 13pt; margin-top: 14pt; color: #222;">${line.replace("## ", "")}</h2>`;
//           if (line.startsWith("### ")) return `<h3 style="font-size: 11pt; margin-top: 10pt; color: #333;">${line.replace("### ", "")}</h3>`;
//           if (line.startsWith("# ")) return `<h1 style="font-size: 15pt; margin-top: 16pt; color: #111;">${line.replace("# ", "")}</h1>`;
//           if (line.startsWith("- ") || line.startsWith("* ")) return `<li style="margin-left: 20px;">${line.replace(/^[-*]\s/, "").replace(/\*\*/g, "")}</li>`;
//           if (line.match(/^\d+\.\s/)) return `<li style="margin-left: 20px;">${line.replace(/^\d+\.\s/, "").replace(/\*\*/g, "")}</li>`;
//           if (line.startsWith("---")) return `<hr style="border: none; border-top: 1px solid #ddd; margin: 16px 0;"/>`;
//           if (line.trim()) return `<p style="margin: 4px 0;">${line.replace(/\*\*/g, "<b>").replace(/\*/g, "")}</p>`;
//           return "";
//         }).join("\n");
//       }).join('<hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;"/>');

//       let transcriptHtml = `<h1 style="font-size: 15pt; margin-top: 20pt; color: #111;">Full Transcript</h1>`;
//       try {
//         const msgs = JSON.parse(transcriptContent);
//         transcriptHtml += msgs.map(m => `<p style="margin: 6px 0;"><b>[${m.time}] ${m.speaker}:</b> ${m.text}</p>`).join("\n");
//       } catch { transcriptHtml += `<p>${transcriptContent}</p>`; }

//       const htmlContent = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><title>Meeting Analysis</title><style>body { font-family: Calibri, sans-serif; font-size: 11pt; line-height: 1.6; color: #333; }</style></head><body><h1 style="font-size: 18pt; color: #111;">Complete Meeting Analysis</h1><p style="color: #888; font-size: 9pt;">${new Date().toLocaleDateString()} &bull; Generated by MeetScribe</p><hr style="border: none; border-top: 2px solid #ccc; margin: 12px 0;"/>${sectionsHtml}<hr style="border: none; border-top: 2px solid #ccc; margin: 20px 0;"/>${transcriptHtml}<hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;"/><p style="color: #aaa; font-size: 8pt; text-align: center;">MeetScribe &bull; Confidential</p></body></html>`;
//       const blob = new Blob(["\ufeff" + htmlContent], { type: "application/msword" });
//       const url = URL.createObjectURL(blob);
//       const a = document.createElement("a");
//       a.href = url; a.download = `meeting-analysis-${Date.now()}.doc`; a.click();
//       URL.revokeObjectURL(url);
//     } else {
//       const doc = new jsPDF();
//       const pageWidth = doc.internal.pageSize.getWidth();
//       const margin = 20; const maxWidth = pageWidth - margin * 2; let y = 25;
//       const checkPage = (needed) => { if (y + needed > 275) { doc.addPage(); y = 20; } };
//       doc.setFontSize(18); doc.setFont("helvetica", "bold"); doc.setTextColor(30, 30, 30);
//       doc.text("Complete Meeting Analysis", margin, y); y += 8;
//       doc.setFontSize(9); doc.setFont("helvetica", "normal"); doc.setTextColor(130, 130, 130);
//       doc.text(`${new Date().toLocaleDateString()} • Generated by MeetScribe`, margin, y); y += 6;
//       doc.setDrawColor(200, 200, 200); doc.line(margin, y, pageWidth - margin, y); y += 10;
//       const cleanContent = stripMd(fullDocument.markdown);
//       const lines = cleanContent.split("\n");
//       for (const line of lines) {
//         const trimmed = line.trim();
//         if (!trimmed) { y += 3; continue; }
//         checkPage(8);
//         if (trimmed === "Full Transcript") {
//           y += 4; doc.setDrawColor(200, 200, 200); doc.line(margin, y, pageWidth - margin, y); y += 8;
//           doc.setFontSize(14); doc.setFont("helvetica", "bold"); doc.setTextColor(30, 30, 30); doc.text(trimmed, margin, y); y += 8;
//         } else if (trimmed.match(/^[A-Z][A-Za-z\s&—]+$/) && trimmed.length < 40) {
//           doc.setFontSize(12); doc.setFont("helvetica", "bold"); doc.setTextColor(50, 50, 50); doc.text(trimmed, margin, y); y += 7;
//         } else {
//           doc.setFontSize(10); doc.setFont("helvetica", "normal"); doc.setTextColor(60, 60, 60);
//           const wrapped = doc.splitTextToSize(trimmed, maxWidth); checkPage(wrapped.length * 5); doc.text(wrapped, margin, y); y += wrapped.length * 5;
//         }
//       }
//       const pageCount = doc.getNumberOfPages();
//       for (let i = 1; i <= pageCount; i++) {
//         doc.setPage(i); doc.setFontSize(8); doc.setTextColor(150, 150, 150);
//         doc.text("MeetScribe • Confidential", margin, 290); doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 25, 290);
//       }
//       doc.save(`meeting-analysis-${Date.now()}.pdf`);
//     }
//     toast({ title: "Downloaded!", description: `Full analysis exported as .${format}` });
//   };

//   const previewMarkdown = useMemo(() => {
//     if (!isAnalyzed) return "";
//     const allSections = allSectionKeys.map(s => mockAnalyzedContent[s.key]).join("\n\n---\n\n");
//     let transcriptText = "";
//     try { const msgs = JSON.parse(transcriptContent); transcriptText = msgs.map(m => `**[${m.time}] ${m.speaker}:** ${m.text}`).join("\n\n"); }
//     catch { transcriptText = transcriptContent; }
//     return `${allSections}\n\n---\n\n# Full Transcript\n\n${transcriptText}`;
//   }, [isAnalyzed, transcriptContent]);

//   return (
//     <div className="lg:flex-1 rounded-2xl border border-border/50 glass-strong gradient-border overflow-hidden flex flex-col">
//       <div className="flex items-center justify-between px-4 pt-4 pb-2">
//         <div className="flex items-center gap-3">
//           <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 shrink-0"><FileText className="h-4 w-4 text-primary" /></div>
//           <div><h3 className="text-sm font-semibold text-foreground">Document Preview</h3><p className="text-[11px] text-muted-foreground">Full analysis export</p></div>
//         </div>
//         <div className="flex items-center gap-3">
//           <div className="flex items-center gap-2 rounded-lg border border-border/40 px-2.5 py-1.5 bg-secondary/30">
//             <span className={`text-[11px] font-medium transition-colors ${format === "doc" ? "text-primary" : "text-muted-foreground"}`}>DOC</span>
//             <button onClick={() => setFormat(format === "doc" ? "pdf" : "doc")} className={`relative h-5 w-9 rounded-full transition-colors duration-200 ${format === "pdf" ? "bg-primary" : "bg-muted"}`}>
//               <div className={`absolute top-0.5 left-0.5 h-4 w-4 rounded-full bg-background shadow-sm transition-transform duration-200 ${format === "pdf" ? "translate-x-4" : "translate-x-0"}`} />
//             </button>
//             <span className={`text-[11px] font-medium transition-colors ${format === "pdf" ? "text-primary" : "text-muted-foreground"}`}>PDF</span>
//           </div>
//           <button onClick={handleDownload} disabled={!isAnalyzed} className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 hover:bg-primary/20 transition-colors disabled:opacity-30 disabled:cursor-not-allowed">
//             <Download className="h-4 w-4 text-primary" />
//           </button>
//         </div>
//       </div>
//       <div className="px-4 pb-4 pt-2 flex-1">
//         <ScrollArea className="h-[440px] rounded-lg overflow-hidden">
//           <div className={`border shadow-sm ${format === "pdf" ? "bg-background border-border/50 p-6" : "bg-background border-border/30 p-5"}`}>
//             {!isAnalyzed ? (
//               <div className="flex flex-col items-center justify-center h-[300px] gap-3 text-center">
//                 <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-muted/50"><FileText className="h-5 w-5 text-muted-foreground/50" /></div>
//                 <p className="text-sm text-muted-foreground">Document preview will appear after analysis...</p>
//               </div>
//             ) : (
//               <div className="space-y-4">
//                 <div className={`border-b pb-4 ${format === "pdf" ? "border-border/40" : "border-primary/20"}`}>
//                   <div className="flex items-center gap-2 mb-2">
//                     <div className={`text-[9px] font-mono uppercase tracking-widest px-2 py-0.5 rounded ${format === "pdf" ? "bg-destructive/10 text-destructive" : "bg-primary/10 text-primary"}`}>.{format}</div>
//                   </div>
//                   <h2 className="text-base font-bold text-foreground">Complete Meeting Analysis</h2>
//                   <p className="text-[11px] text-muted-foreground mt-1">{new Date().toLocaleDateString()} • Generated by MeetScribe</p>
//                 </div>
//                 <div className="prose prose-sm dark:prose-invert max-w-none text-foreground/90">
//                   <ReactMarkdown components={{
//                     h1: ({ children }) => <h1 className="text-base font-bold mt-5 mb-2 text-foreground border-t border-border/30 pt-4">{children}</h1>,
//                     h2: ({ children }) => <h2 className="text-sm font-bold mt-3 mb-1.5 text-foreground">{children}</h2>,
//                     h3: ({ children }) => <h3 className="text-xs font-bold mt-2 mb-1 text-foreground">{children}</h3>,
//                     p: ({ children }) => <p className="text-xs leading-relaxed mb-2 text-foreground/85">{children}</p>,
//                     ul: ({ children }) => <ul className="list-disc pl-4 mb-2 space-y-0.5 text-xs">{children}</ul>,
//                     ol: ({ children }) => <ol className="list-decimal pl-4 mb-2 space-y-0.5 text-xs">{children}</ol>,
//                     li: ({ children }) => <li className="text-xs leading-relaxed text-foreground/85">{children}</li>,
//                     strong: ({ children }) => <strong className="font-semibold text-foreground">{children}</strong>,
//                     hr: () => <hr className="border-border/30 my-4" />,
//                   }}>{previewMarkdown}</ReactMarkdown>
//                 </div>
//                 {format === "pdf" && (
//                   <div className="border-t border-border/30 pt-3 mt-6 flex items-center justify-between">
//                     <span className="text-[9px] text-muted-foreground/50 font-mono">MeetScribe • Confidential</span>
//                     <span className="text-[9px] text-muted-foreground/50 font-mono">Page 1 of 1</span>
//                   </div>
//                 )}
//               </div>
//             )}
//           </div>
//         </ScrollArea>
//       </div>
//     </div>
//   );
// };

// export default DocumentPreview;

import { useState, useMemo, useRef, useCallback } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import ReactMarkdown from "react-markdown";
import { FileText, Download, Loader2 } from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";
import { toast } from "@/hooks/use-toast";
import { allSectionKeys, mockAnalyzedContent } from "./data";

const DocumentPreview = ({ isAnalyzed, transcriptContent }) => {
  const [format, setFormat] = useState("pdf");
  const [downloading, setDownloading] = useState(false);
  const contentRef = useRef(null);

  const previewMarkdown = useMemo(() => {
    if (!isAnalyzed) return "";
    const allSections = allSectionKeys.map(s => mockAnalyzedContent[s.key]).join("\n\n---\n\n");
    let transcriptText = "";
    try {
      const msgs = JSON.parse(transcriptContent);
      transcriptText = msgs.map(m => `**[${m.time}] ${m.speaker}:** ${m.text}`).join("\n\n");
    } catch {
      transcriptText = transcriptContent;
    }
    return `${allSections}\n\n---\n\n# Full Transcript\n\n${transcriptText}`;
  }, [isAnalyzed, transcriptContent]);

  const buildStyledHtml = useCallback(() => {
    const fontFamily = format === "doc"
      ? "'Calibri', 'Segoe UI', sans-serif"
      : "'Helvetica', 'Arial', sans-serif";
    const isDoc = format === "doc";

    const headerFontSize = isDoc ? "16pt" : "18pt";
    const h1Size = isDoc ? "15pt" : "14pt";
    const h2Size = isDoc ? "13pt" : "12pt";
    const h3Size = "11pt";
    const bodySize = isDoc ? "11pt" : "10pt";
    const lineH = isDoc ? "1.6" : "1.5";
    const h2Color = isDoc ? "#2b579a" : "#333";
    const borderTop = isDoc ? "1px solid #ccc" : "2px solid #333";

    const sectionsHtml = allSectionKeys.map(s => {
      const content = mockAnalyzedContent[s.key];
      return content.split("\n").map(line => {
        if (line.startsWith("### ")) return `<h3 style="font-size: ${h3Size}; font-weight: bold; color: #444; margin-top: 10px; margin-bottom: 3px; font-family: ${fontFamily};">${line.replace("### ", "")}</h3>`;
        if (line.startsWith("## ")) return `<h2 style="font-size: ${h2Size}; font-weight: bold; color: ${h2Color}; margin-top: 14px; margin-bottom: 4px; font-family: ${fontFamily};">${line.replace("## ", "")}</h2>`;
        if (line.startsWith("# ")) return `<h1 style="font-size: ${h1Size}; font-weight: bold; color: #1a1a1a; margin-top: 20px; margin-bottom: 6px; padding-top: 12px; border-top: 1px solid #ddd; font-family: ${fontFamily};">${line.replace("# ", "")}</h1>`;
        if (line.startsWith("- ") || line.startsWith("* ")) {
          const text = line.replace(/^[-*]\s/, "").replace(/\*\*(.*?)\*\*/g, '<strong style="font-weight: 600; color: #222;">$1</strong>');
          return `<li style="font-size: ${bodySize}; line-height: ${lineH}; color: #444; margin-bottom: 2px; margin-left: 20px;">${text}</li>`;
        }
        if (line.match(/^\d+\.\s/)) {
          const text = line.replace(/^\d+\.\s/, "").replace(/\*\*(.*?)\*\*/g, '<strong style="font-weight: 600; color: #222;">$1</strong>');
          return `<li style="font-size: ${bodySize}; line-height: ${lineH}; color: #444; margin-bottom: 2px; margin-left: 20px;">${text}</li>`;
        }
        if (line.startsWith("---")) return `<hr style="border: none; border-top: 1px solid #ddd; margin: 16px 0;"/>`;
        if (line.trim()) {
          const text = line.replace(/\*\*(.*?)\*\*/g, '<strong style="font-weight: 600; color: #222;">$1</strong>');
          return `<p style="font-size: ${bodySize}; line-height: ${lineH}; color: #444; margin-bottom: 6px; margin-top: 2px;">${text}</p>`;
        }
        return "";
      }).join("\n");
    }).join('<hr style="border: none; border-top: 1px solid #ddd; margin: 16px 0;"/>');

    let transcriptHtml = `<h1 style="font-size: ${h1Size}; font-weight: bold; color: #1a1a1a; margin-top: 20px; margin-bottom: 6px; padding-top: 12px; border-top: 1px solid #ddd; font-family: ${fontFamily};">Full Transcript</h1>`;
    try {
      const msgs = JSON.parse(transcriptContent);
      transcriptHtml += msgs.map(m =>
        `<p style="font-size: ${bodySize}; line-height: ${lineH}; color: #444; margin-bottom: 6px; margin-top: 2px;"><strong style="font-weight: 600; color: #222;">[${m.time}] ${m.speaker}:</strong> ${m.text}</p>`
      ).join("\n");
    } catch {
      transcriptHtml += `<p style="font-size: ${bodySize}; line-height: ${lineH}; color: #444;">${transcriptContent}</p>`;
    }

    return `<html><head><meta charset="utf-8"><title>Meeting Analysis</title></head><body style="font-family: ${fontFamily}; color: #333; padding: ${isDoc ? '50px 45px' : '60px 50px'}; line-height: ${lineH}; font-size: ${bodySize};">
      <h1 style="font-size: ${headerFontSize}; font-weight: bold; color: #1a1a1a; margin: 0 0 4px 0; font-family: ${fontFamily};">Complete Meeting Analysis</h1>
      <p style="font-size: 9pt; color: #999; margin: 0 0 8px 0;">${new Date().toLocaleDateString()} • Generated by Kothalipi</p>
      <div style="border-top: ${borderTop}; margin-top: 4px; margin-bottom: 16px;"></div>
      ${sectionsHtml}
      <hr style="border: none; border-top: 1px solid #ddd; margin: 16px 0;"/>
      ${transcriptHtml}
      <div style="border-top: 1px solid #e0e0e0; margin-top: 30px; padding-top: 8px; display: flex; justify-content: space-between;">
        <span style="font-size: 8pt; color: #aaa; font-family: ${fontFamily};">Kothalipi • Confidential</span>
      </div>
    </body></html>`;
  }, [format, transcriptContent]);

  const handleDownload = async () => {
    if (!isAnalyzed) return;
    setDownloading(true);

    try {
      if (format === "doc") {
        const htmlContent = buildStyledHtml();
        const blob = new Blob(["\ufeff" + htmlContent], { type: "application/msword" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `kothalipi-analysis-${Date.now()}.doc`;
        a.click();
        URL.revokeObjectURL(url);
      } else {
        // PDF: capture the actual preview DOM via html2canvas
        const element = contentRef.current;
        if (!element) return;

        const canvas = await html2canvas(element, {
          scale: 2,
          useCORS: true,
          logging: false,
          backgroundColor: "#ffffff",
        });

        const imgWidth = 210; // A4 width mm
        const pageHeight = 297; // A4 height mm
        const imgHeight = (canvas.height * imgWidth) / canvas.width;

        const pdf = new jsPDF("p", "mm", "a4");
        const imgData = canvas.toDataURL("image/png");

        let heightLeft = imgHeight;
        let position = 0;

        pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;

        while (heightLeft > 0) {
          position = heightLeft - imgHeight;
          pdf.addPage();
          pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
          heightLeft -= pageHeight;
        }

        pdf.save(`kothalipi-analysis-${Date.now()}.pdf`);
      }
      toast({ title: "Downloaded!", description: `Full analysis exported as .${format}` });
    } catch (err) {
      console.error("Download error:", err);
      toast({ title: "Download failed", description: "Something went wrong during export.", variant: "destructive" });
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="lg:flex-1 rounded-2xl border border-border/50 glass-strong gradient-border overflow-hidden flex flex-col">
      <div className="flex items-center justify-between px-4 pt-4 pb-2">
        <div className="flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 shrink-0">
            <FileText className="h-4 w-4 text-primary" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-foreground">Document Preview</h3>
            <p className="text-[11px] text-muted-foreground">Full analysis export</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 rounded-lg border border-border/40 px-2.5 py-1.5 bg-secondary/30">
            <span className={`text-[11px] font-medium transition-colors ${format === "doc" ? "text-primary" : "text-muted-foreground"}`}>DOC</span>
            <button
              onClick={() => setFormat(format === "doc" ? "pdf" : "doc")}
              className={`relative h-5 w-9 rounded-full transition-colors duration-200 ${format === "pdf" ? "bg-primary" : "bg-muted"}`}
            >
              <div className={`absolute top-0.5 left-0.5 h-4 w-4 rounded-full bg-background shadow-sm transition-transform duration-200 ${format === "pdf" ? "translate-x-4" : "translate-x-0"}`} />
            </button>
            <span className={`text-[11px] font-medium transition-colors ${format === "pdf" ? "text-primary" : "text-muted-foreground"}`}>PDF</span>
          </div>
          <button
            onClick={handleDownload}
            disabled={!isAnalyzed || downloading}
            className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 hover:bg-primary/20 transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
          >
            {downloading ? <Loader2 className="h-4 w-4 text-primary animate-spin" /> : <Download className="h-4 w-4 text-primary" />}
          </button>
        </div>
      </div>
      <div className="px-4 pb-4 pt-2 flex-1">
        <ScrollArea className="h-[440px] rounded-lg overflow-hidden">
          <div className="bg-[#e8e8e8] p-4 min-h-[440px] flex justify-center">
            {!isAnalyzed ? (
              <div className="flex flex-col items-center justify-center h-[300px] gap-3 text-center w-full">
                <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-muted/50">
                  <FileText className="h-5 w-5 text-muted-foreground/50" />
                </div>
                <p className="text-sm text-muted-foreground">Document preview will appear after analysis...</p>
              </div>
            ) : (
              <div
                ref={contentRef}
                className="w-full max-w-[612px] bg-white shadow-lg"
                style={{
                  fontFamily: format === "doc" ? "'Calibri', 'Segoe UI', sans-serif" : "'Helvetica', 'Arial', sans-serif",
                  color: "#333",
                  padding: format === "pdf" ? "60px 50px" : "50px 45px",
                  lineHeight: format === "doc" ? "1.6" : "1.5",
                  fontSize: format === "doc" ? "11pt" : "10pt",
                  minHeight: "792px",
                  position: "relative",
                }}
              >
                {format === "doc" && (
                  <div className="absolute top-0 left-0 right-0 h-6 bg-[#f0f0f0] border-b border-[#ccc] flex items-end px-[45px]">
                    {Array.from({ length: 17 }, (_, i) => (
                      <div key={i} className="flex-1 border-r border-[#bbb] h-2 relative">
                        <span className="absolute -bottom-3 left-1/2 -translate-x-1/2 text-[7px] text-[#888]">{i + 1}</span>
                      </div>
                    ))}
                  </div>
                )}

                <div style={{ marginBottom: format === "pdf" ? 16 : 20 }}>
                  <h1 style={{
                    fontSize: format === "pdf" ? "18pt" : "16pt",
                    fontWeight: "bold",
                    color: "#1a1a1a",
                    margin: "0 0 4px 0",
                    fontFamily: format === "doc" ? "'Calibri', sans-serif" : "'Helvetica', sans-serif",
                  }}>Complete Meeting Analysis</h1>
                  <p style={{ fontSize: "9pt", color: "#999", margin: "0 0 8px 0" }}>
                    {new Date().toLocaleDateString()} • Generated by Kothalipi
                  </p>
                  <div style={{ borderTop: format === "pdf" ? "2px solid #333" : "1px solid #ccc", marginTop: 4 }} />
                </div>

                <div>
                  <ReactMarkdown components={{
                    h1: ({ children }) => (
                      <h1 style={{
                        fontSize: format === "pdf" ? "14pt" : "15pt",
                        fontWeight: "bold",
                        color: "#1a1a1a",
                        marginTop: 20,
                        marginBottom: 6,
                        paddingTop: 12,
                        borderTop: "1px solid #ddd",
                        fontFamily: format === "doc" ? "'Calibri', sans-serif" : "'Helvetica', sans-serif",
                      }}>{children}</h1>
                    ),
                    h2: ({ children }) => (
                      <h2 style={{
                        fontSize: format === "pdf" ? "12pt" : "13pt",
                        fontWeight: "bold",
                        color: format === "doc" ? "#2b579a" : "#333",
                        marginTop: 14,
                        marginBottom: 4,
                        fontFamily: format === "doc" ? "'Calibri', sans-serif" : "'Helvetica', sans-serif",
                      }}>{children}</h2>
                    ),
                    h3: ({ children }) => (
                      <h3 style={{
                        fontSize: "11pt",
                        fontWeight: "bold",
                        color: "#444",
                        marginTop: 10,
                        marginBottom: 3,
                      }}>{children}</h3>
                    ),
                    p: ({ children }) => (
                      <p style={{
                        fontSize: format === "pdf" ? "10pt" : "11pt",
                        lineHeight: format === "doc" ? "1.6" : "1.5",
                        color: "#444",
                        marginBottom: 6,
                        marginTop: 2,
                      }}>{children}</p>
                    ),
                    ul: ({ children }) => (
                      <ul style={{
                        listStyleType: "disc",
                        paddingLeft: 20,
                        marginBottom: 8,
                        fontSize: format === "pdf" ? "10pt" : "11pt",
                        color: "#444",
                      }}>{children}</ul>
                    ),
                    ol: ({ children }) => (
                      <ol style={{
                        listStyleType: "decimal",
                        paddingLeft: 20,
                        marginBottom: 8,
                        fontSize: format === "pdf" ? "10pt" : "11pt",
                        color: "#444",
                      }}>{children}</ol>
                    ),
                    li: ({ children }) => (
                      <li style={{
                        fontSize: format === "pdf" ? "10pt" : "11pt",
                        lineHeight: format === "doc" ? "1.6" : "1.5",
                        color: "#444",
                        marginBottom: 2,
                      }}>{children}</li>
                    ),
                    strong: ({ children }) => <strong style={{ fontWeight: 600, color: "#222" }}>{children}</strong>,
                    hr: () => <hr style={{ border: "none", borderTop: "1px solid #ddd", margin: "16px 0" }} />,
                  }}>{previewMarkdown}</ReactMarkdown>
                </div>

                <div style={{
                  position: "absolute",
                  bottom: format === "pdf" ? 30 : 25,
                  left: format === "pdf" ? 50 : 45,
                  right: format === "pdf" ? 50 : 45,
                  display: "flex",
                  justifyContent: "space-between",
                  borderTop: "1px solid #e0e0e0",
                  paddingTop: 8,
                }}>
                  <span style={{ fontSize: "8pt", color: "#aaa", fontFamily: format === "pdf" ? "'Helvetica', sans-serif" : "'Calibri', sans-serif" }}>
                    Kothalipi • Confidential
                  </span>
                  <span style={{ fontSize: "8pt", color: "#aaa", fontFamily: format === "pdf" ? "'Helvetica', sans-serif" : "'Calibri', sans-serif" }}>
                    Page 1 of 1
                  </span>
                </div>
              </div>
            )}
          </div>
        </ScrollArea>
      </div>
    </div>
  );
};

export default DocumentPreview;