import { Download, Mic, FileDown, ArrowRightFromLine, BarChart3 } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { mockAnalyzedContent } from "./data";

const ExportsCard = ({ isRecording, isAnalyzed, audioBlob }) => {
  const handleDownloadRecording = async () => {
    if (!audioBlob) return;
    try {
      const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
      const arrayBuffer = await audioBlob.arrayBuffer();
      const audioBuffer = await audioCtx.decodeAudioData(arrayBuffer);
      const samples = audioBuffer.getChannelData(0);
      const sampleRate = audioBuffer.sampleRate;

      // Convert to 16-bit PCM
      const pcmData = new Int16Array(samples.length);
      for (let i = 0; i < samples.length; i++) {
        const s = Math.max(-1, Math.min(1, samples[i]));
        pcmData[i] = s < 0 ? s * 0x8000 : s * 0x7FFF;
      }

      const { Mp3Encoder } = await import("@breezystack/lamejs");

      const mp3Encoder = new Mp3Encoder(1, sampleRate, 128);
      const mp3Chunks = [];
      const blockSize = 1152;
      for (let i = 0; i < pcmData.length; i += blockSize) {
        const chunk = pcmData.subarray(i, i + blockSize);
        const mp3buf = mp3Encoder.encodeBuffer(chunk);
        if (mp3buf.length > 0) mp3Chunks.push(new Uint8Array(mp3buf));
      }
      const end = mp3Encoder.flush();
      if (end.length > 0) mp3Chunks.push(new Uint8Array(end));

      const mp3Blob = new Blob(mp3Chunks, { type: "audio/mpeg" });
      const url = URL.createObjectURL(mp3Blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `recording-${Date.now()}.mp3`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      await audioCtx.close();

      toast({ title: "Download started", description: "Your MP3 recording is downloading." });
    } catch (err) {
      console.error("MP3 conversion failed, downloading as webm:", err);
      // Fallback: download raw webm
      const url = URL.createObjectURL(audioBlob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `recording-${Date.now()}.webm`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast({ title: "Downloaded as WebM", description: "MP3 conversion failed, saved as .webm instead." });
    }
  };

  const handleDownloadTranscript = () => {
    const content = mockAnalyzedContent.transcript;
    let text;
    try {
      const msgs = JSON.parse(content);
      text = msgs.map((m) => `[${m.time}] ${m.speaker}: ${m.text}`).join("\n\n");
    } catch { text = content; }
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `transcription-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadTranslation = () => {
    const blob = new Blob(["[Translated transcription will be generated by backend]"], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `translated-transcription-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadAnalysis = () => {
    const content = Object.entries(mockAnalyzedContent)
      .filter(([key]) => key !== "transcript")
      .map(([key, val]) => `=== ${key.toUpperCase()} ===\n\n${val}`)
      .join("\n\n\n");
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `analysis-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const items = [
    { icon: Mic, label: "Audio Recording", onClick: handleDownloadRecording, disabled: isRecording || !audioBlob, desc: ".mp3" },
    { icon: FileDown, label: "Transcription", onClick: handleDownloadTranscript, disabled: !isAnalyzed, desc: ".txt" },
    { icon: ArrowRightFromLine, label: "Translation (EN)", onClick: handleDownloadTranslation, disabled: !isAnalyzed, desc: ".txt" },
    { icon: BarChart3, label: "Full Analysis", onClick: handleDownloadAnalysis, disabled: !isAnalyzed, desc: ".txt" },
  ];

  return (
    <div className="rounded-2xl border border-border/50 glass-strong gradient-border p-4 flex flex-col gap-2 flex-1">
      <div className="flex items-center gap-2 mb-1">
        <Download className="h-3.5 w-3.5 text-green-600" />
        <span className="text-[11px] font-semibold uppercase tracking-wider text-green-600">Exports</span>
      </div>
      {items.map((item, idx) => (
        <button key={idx} onClick={item.onClick} disabled={item.disabled} className="group w-full flex items-center gap-3 rounded-xl px-3 py-2.5 text-left transition-all duration-200 hover:bg-secondary/60 disabled:opacity-25 disabled:cursor-not-allowed disabled:hover:bg-transparent">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/8 group-hover:bg-primary/15 transition-colors shrink-0"><item.icon className="h-3.5 w-3.5 text-primary" /></div>
          <div className="flex-1 min-w-0">
            <p className="text-xs font-medium text-foreground truncate">{item.label}</p>
            <p className="text-[10px] text-muted-foreground/60">{item.desc}</p>
          </div>
        </button>
      ))}
    </div>
  );
};

export default ExportsCard;
