"""meeting_id_field added

Revision ID: 3728c08d994d
Revises: 39261d3dca6b
Create Date: 2026-05-04 09:39:37.972792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3728c08d994d'
down_revision: Union[str, Sequence[str], None] = '39261d3dca6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiotranscription', sa.Column('meeting_id', sa.Uuid(), nullable=True))
    op.add_column('audiotranslation', sa.Column('meeting_id', sa.Uuid(), nullable=True))
    op.add_column('meetinganalysis', sa.Column('meeting_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetinganalysis', 'meeting_id')
    op.drop_column('audiotranslation', 'meeting_id')
    op.drop_column('audiotranscription', 'meeting_id')
    # ### end Alembic commands ###
