"""analysis field make null

Revision ID: 39261d3dca6b
Revises: b5d2b5c5171d
Create Date: 2026-04-02 14:52:16.396999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39261d3dca6b'
down_revision: Union[str, Sequence[str], None] = 'b5d2b5c5171d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processingjob_celery_task_id'), table_name='processingjob')
    op.drop_index(op.f('ix_processingjob_id'), table_name='processingjob')
    op.drop_index(op.f('ix_processingjob_status'), table_name='processingjob')
    op.drop_index(op.f('ix_processingjob_user_id'), table_name='processingjob')
    op.drop_table('processingjob')
    op.alter_column('meetinganalysis', 'content_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meetinganalysis', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meetinganalysis', 'business_insights',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meetinganalysis', 'technical_insights',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetinganalysis', 'technical_insights',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('meetinganalysis', 'business_insights',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('meetinganalysis', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('meetinganalysis', 'content_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('processingjob',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('stage', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('celery_task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('audio_transcription_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('audio_translation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('meeting_analysis_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['audio_transcription_id'], ['audiotranscription.id'], name=op.f('processingjob_audio_transcription_id_fkey')),
    sa.ForeignKeyConstraint(['audio_translation_id'], ['audiotranslation.id'], name=op.f('processingjob_audio_translation_id_fkey')),
    sa.ForeignKeyConstraint(['meeting_analysis_id'], ['meetinganalysis.id'], name=op.f('processingjob_meeting_analysis_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('processingjob_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('processingjob_pkey'))
    )
    op.create_index(op.f('ix_processingjob_user_id'), 'processingjob', ['user_id'], unique=False)
    op.create_index(op.f('ix_processingjob_status'), 'processingjob', ['status'], unique=False)
    op.create_index(op.f('ix_processingjob_id'), 'processingjob', ['id'], unique=False)
    op.create_index(op.f('ix_processingjob_celery_task_id'), 'processingjob', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###
