"""refactor translation to audiotranslation

Revision ID: 5a5954f6012f
Revises: e89006206c19
Create Date: 2026-02-03 10:56:48.328339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a5954f6012f'
down_revision: Union[str, Sequence[str], None] = 'e89006206c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiotranslation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audio_transcription_id', sa.Uuid(), nullable=False),
    sa.Column('source_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('translated_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audio_transcription_id'], ['audiotranscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audiotranslation_id'), 'audiotranslation', ['id'], unique=False)
    op.drop_index(op.f('ix_translation_id'), table_name='translation')
    op.drop_table('translation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('audio_transcription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('translated_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['audio_transcription_id'], ['audiotranscription.id'], name=op.f('translation_audio_transcription_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('translation_pkey'))
    )
    op.create_index(op.f('ix_translation_id'), 'translation', ['id'], unique=False)
    op.drop_index(op.f('ix_audiotranslation_id'), table_name='audiotranslation')
    op.drop_table('audiotranslation')
    # ### end Alembic commands ###
