"""added user link to related models

Revision ID: b5d2b5c5171d
Revises: c630c37d3aa8
Create Date: 2026-02-08 11:15:49.093789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5d2b5c5171d'
down_revision: Union[str, Sequence[str], None] = 'c630c37d3aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiotranslation', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'audiotranslation', 'user', ['user_id'], ['id'])
    op.add_column('meetinganalysis', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'meetinganalysis', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetinganalysis', type_='foreignkey')
    op.drop_column('meetinganalysis', 'user_id')
    op.drop_constraint(None, 'audiotranslation', type_='foreignkey')
    op.drop_column('audiotranslation', 'user_id')
    # ### end Alembic commands ###
