"""meeting_id_field changed to task_id

Revision ID: e1a6de1865b5
Revises: 3728c08d994d
Create Date: 2026-05-04 16:18:57.855006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1a6de1865b5'
down_revision: Union[str, Sequence[str], None] = '3728c08d994d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiotranscription', sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_audiotranscription_task_id'), 'audiotranscription', ['task_id'], unique=False)
    op.drop_column('audiotranscription', 'meeting_id')
    op.add_column('audiotranslation', sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_audiotranslation_task_id'), 'audiotranslation', ['task_id'], unique=False)
    op.drop_column('audiotranslation', 'meeting_id')
    op.add_column('meetinganalysis', sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_meetinganalysis_task_id'), 'meetinganalysis', ['task_id'], unique=False)
    op.drop_column('meetinganalysis', 'meeting_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetinganalysis', sa.Column('meeting_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_meetinganalysis_task_id'), table_name='meetinganalysis')
    op.drop_column('meetinganalysis', 'task_id')
    op.add_column('audiotranslation', sa.Column('meeting_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audiotranslation_task_id'), table_name='audiotranslation')
    op.drop_column('audiotranslation', 'task_id')
    op.add_column('audiotranscription', sa.Column('meeting_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audiotranscription_task_id'), table_name='audiotranscription')
    op.drop_column('audiotranscription', 'task_id')
    # ### end Alembic commands ###
