"""Add MeetingAnalysis model

Revision ID: f743a631c589
Revises: 5a5954f6012f
Create Date: 2026-02-03 11:16:25.138877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f743a631c589'
down_revision: Union[str, Sequence[str], None] = '5a5954f6012f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetinganalysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audio_translation_id', sa.Uuid(), nullable=False),
    sa.Column('content_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_insights', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('technical_insights', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_items', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('key_topics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audio_translation_id'], ['audiotranslation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetinganalysis_id'), 'meetinganalysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetinganalysis_id'), table_name='meetinganalysis')
    op.drop_table('meetinganalysis')
    # ### end Alembic commands ###
